keys:
    - &geoffmbp age1j889lj8ezuuu9cuzffcxkg62d502r6058ckr20gnsgflguuu59psy8af6g
    - &prodec2 age1tkvqy82ny4v7vlv8y7nuqaep86ztsdryysgw3pes3s8gd7kecfyskvp445

creation_rules:
  - path_regex: \.sops$
    shamir_threshold: 1
    encrypted_regex: "^(GOATCOUNTER_API_KEY)$"
    key_groups:
    - age:
        - *geoffmbp
        - *prodec2
