const config = {
    commentFilter: 'QP',
    aprsServer: "167.114.2.176",
    aprsPort: 14580,
    aprsCall: "NOCALL",
    databasePath: process.env.DB_PATH || "../aprs.db",
    logLevel: process.env.NODE_ENV === 'production' ? 'info' : 'debug',
    qsoParties: {
        "AL": {
            stateAbbr: "AL",
            operationTitle: `Alabama QSO Party`,
            operationInstructions: `To be listed on this map, put <u>ALQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "ALQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `ALQP`,
            kmlFile: 'OverlayAlabamaRev5.kml',
        },
        "AZ": {
            stateAbbr: "AZ",
            operationTitle: `Arizona QSO Party`,
            operationInstructions: `To be listed on this map, put <u>AZQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "AZQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `AZQP`,
            kmlFile: 'OverlayArizonaRev3.kml',

        },
        "AR": {
            stateAbbr: "AR",
            operationTitle: `Arkansas QSO Party`,
            operationInstructions: `To be listed on this map, put <u>ARQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "ARQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `ARQP`,
            kmlFile: 'OverlayArkansasRev5.kml',
        },
        "CA": {
            stateAbbr: "CA",
            operationTitle: `California QSO Party`,
            operationInstructions: `To be listed on this map, put <u>CAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "CAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `CAQP`,
            kmlFile: 'OverlayCaliforniaRev4.kml',

        },
        "CO": {
            stateAbbr: "CO",
            operationTitle: `Colorado QSO Party`,
            operationInstructions: `To be listed on this map, put <u>COQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "COQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `COQP`,
            kmlFile: 'OverlayColoradoRev6.kml',
        },
        "CT": {
            stateAbbr: "CT",
            operationTitle: `Connecticut QSO Party`,
            operationInstructions: `To be listed on this map, put <u>CTQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "CTQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `CTQP`,
            kmlFile: 'OverlayConnecticutRev3.kml',
        },
        "DE": {
            stateAbbr: "DE",
            operationTitle: `Delaware QSO Party`,
            operationInstructions: `To be listed on this map, put <u>DEQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "DEQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `DEQP`,
            kmlFile: 'OverlayDelawareRev3.kml',
        },
        "FL": {
            stateAbbr: "FL",
            operationTitle: `Florida QSO Party`,
            operationInstructions: `To be listed on this map, put <u>FLQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "FLQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `FLQP`,
            kmlFile: 'OverlayFloridaRev8.kml',
        },
        "GA": {
            stateAbbr: "GA",
            operationTitle: `Georgia QSO Party`,
            operationInstructions: `To be listed on this map, put <u>GAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "GAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `GAQP`,
            kmlFile: 'OverlayGeorgiaRev3.kml',
        },
        "HI": {
            stateAbbr: "HI",
            operationTitle: `Hawaii QSO Party`,
            operationInstructions: `To be listed on this map, put <u>HIQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "HIQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `HIQP`,
            kmlFile: 'OverlayHawaiiRev2.kml',
        },
        "ID": {
            stateAbbr: "ID",
            operationTitle: `Idaho QSO Party`,
            operationInstructions: `To be listed on this map, put <u>IDQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "IDQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `IDQP`,
            kmlFile: 'OverlayIdahoRev4.kml',
        },
        "IL": {
            stateAbbr: "IL",
            operationTitle: `Illinois QSO Party`,
            operationInstructions: `To be listed on this map, put <u>ILQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "ILQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `ILQP`,
            kmlFile: 'OverlayIllinoisRev3.kml',
        },
        "IN": {
            stateAbbr: "IN",
            operationTitle: `Indiana QSO Party`,
            operationInstructions: `To be listed on this map, put <u>INQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "INQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `INQP`,
            kmlFile: 'OverlayIndianaRev3.kml',
        },
        "IA": {
            stateAbbr: "IA",
            operationTitle: `Iowa QSO Party`,
            operationInstructions: `To be listed on this map, put <u>IAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "IAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `IAQP`,
            kmlFile: 'OverlayIowaRev3.kml',
        },
        "KS": {
            stateAbbr: "KS",
            operationTitle: `Kansas QSO Party`,
            operationInstructions: `To be listed on this map, put <u>KSQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "KSQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `KSQP`,
            kmlFile: 'OverlayKansasRev3.kml',
        },
        "KY": {
            stateAbbr: "KY",
            operationTitle: `Kentucky QSO Party`,
            operationInstructions: `To be listed on this map, put <u>KYQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "KYQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `KYQP`,
            kmlFile: 'OverlayKentuckyRev3.kml',
        },
        "LA": {
            stateAbbr: "LA",
            operationTitle: `Louisiana QSO Party`,
            operationInstructions: `To be listed on this map, put <u>LAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "LAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `LAQP`,
            kmlFile: 'OverlayLouisianaRev06.kml',
        },
        "ME": {
            stateAbbr: "ME",
            operationTitle: `Maine QSO Party`,
            operationInstructions: `To be listed on this map, put <u>MEQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MEQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MEQP`,
            kmlFile: 'OverlayMaineRev3.kml',
        },
        "MD": {
            stateAbbr: "MD",
            operationTitle: `Maryland QSO Party`,
            operationInstructions: `To be listed on this map, put <u>MDQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MDQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MDQP`,
            kmlFile: 'OverlayMaryland-DCRev4.kml',
        },
        "MA": {
            stateAbbr: "MA",
            operationTitle: `Massachusetts QSO Party`,
            operationInstructions: `To be listed on this map, put <u>MAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MAQP`,
            kmlFile: 'OverlayMassachusettsRev6.kml',
        },
        "MI": {
            stateAbbr: "MI",
            operationTitle: `Michigan QSO Party`,
            operationInstructions: `To be listed on this map, put <u>MIQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MIQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MIQP`,
            kmlFile: 'OverlayMichiganRev4.kml',
        },
        "MN": {
            stateAbbr: "MN",
            operationTitle: `Minnesota QSO Party`,
            operationInstructions: `To be listed on this map, put <u>MNQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MNQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MNQP`,
            kmlFile: 'OverlayMinnesotaRev3.kml',
        },
        "MS": {
            stateAbbr: "MS",
            operationTitle: `Mississippi QSO Party`,
            operationInstructions: `To be listed on this map, put <u>MSQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MSQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MSQP`,
            kmlFile: 'OverlayMississippiRev4.kml',
        },
        "MO": {
            stateAbbr: "MO",
            operationTitle: `Missouri QSO Party`,
            operationInstructions: `To be listed on this map, put <u>MOQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MOQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MOQP`,
            kmlFile: 'OverlayMissouriRev3.kml',
        },
        "MT": {
            stateAbbr: "MT",
            operationTitle: `Montana QSO Party`,
            operationInstructions: `To be listed on this map, put <u>MTQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MTQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MTQP`,
            kmlFile: 'OverlayMontanaRev3.kml',
        },
        "NE": {
            stateAbbr: "NE",
            operationTitle: `Nebraska QSO Party`,
            operationInstructions: `To be listed on this map, put <u>NEQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NEQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NEQP`,
            kmlFile: 'OverlayNebraskaRev3.kml',
        },
        "NH": {
            stateAbbr: "NH",
            operationTitle: `New Hampshire QSO Party`,
            operationInstructions: `To be listed on this map, put <u>NHQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NHQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NHQP`,
            kmlFile: 'OverlayNewHampshire_NHQP_Rev3.kml',
        },
        "NJ": {
            stateAbbr: "NJ",
            operationTitle: `New Jersey QSO Party`,
            operationInstructions: `To be listed on this map, put <u>NJQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NJQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NJQP`,
            kmlFile: 'OverlayNewJerseyRev3.kml',
        },
        "NM": {
            stateAbbr: "NM",
            operationTitle: `New Mexico QSO Party`,
            operationInstructions: `To be listed on this map, put <u>NMQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NMQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NMQP`,
            kmlFile: 'OverlayNewMexicoRev3.kml',
        },
        "NY": {
            stateAbbr: "NY",
            operationTitle: `NY QSO Party`,
            operationInstructions: `To be listed on this map, put <u>NYQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NYQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NYQP`,
            kmlFile: 'OverlayNewYorkRev4.kml',
        },
        "NC": {
            stateAbbr: "NC",
            operationTitle: `North Carolina QSO Party`,
            operationInstructions: `To be listed on this map, put <u>NCQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NCQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NCQP`,
            kmlFile: 'OverlayNorthCarolinaRev3.kml',
        },
        "ND": {
            stateAbbr: "ND",
            operationTitle: `North Dakota QSO Party`,
            operationInstructions: `To be listed on this map, put <u>NDQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NDQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NDQP`,
            kmlFile: 'OverlayNorthDakotaRev3.kml',
        },
        "NV": {
            stateAbbr: "NV",
            operationTitle: `Nevada QSO Party`,
            operationInstructions: `To be listed on this map, put <u>NVQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NVQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NVQP`,
            kmlFile: 'OverlayNevada_NVQP_Rev3.kml',
        },
        "OH": {
            stateAbbr: "OH",
            operationTitle: `Ohio QSO Party`,
            operationInstructions: `To be listed on this map, put <u>OHQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "OHQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `OHQP`,
            kmlFile: 'OverlayOhioRev4.kml',
        },
        "OK": {
            stateAbbr: "OK",
            operationTitle: `Oklahoma QSO Party`,
            operationInstructions: `To be listed on this map, put <u>OKQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "OKQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `OKQP`,
            kmlFile: 'OverlayOklahomaRev3.kml',
        },
        "OR": {
            stateAbbr: "OR",
            operationTitle: `Oregon QSO Party`,
            operationInstructions: `To be listed on this map, put <u>ORQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "ORQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `ORQP`,
            kmlFile: 'OverlayOregonRev3.kml',
        },
        "PA": {
            stateAbbr: "PA",
            operationTitle: `Pennsylvania QSO Party`,
            operationInstructions: `To be listed on this map, put <u>PAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "PAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `PAQP`,
            kmlFile: 'OverlayPennsylvaniaRev3.kml',
        },
        "RI": {
            stateAbbr: "RI",
            operationTitle: `Rhode Island QSO Party`,
            operationInstructions: `To be listed on this map, put <u>RIQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "RIQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `RIQP`,
            kmlFile: 'OverlayRhodeIslandRev7.kml',
        },
        "SC": {
            stateAbbr: "SC",
            operationTitle: `South Carolina QSO Party`,
            operationInstructions: `To be listed on this map, put <u>SCQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Ex: "SCQP 14.230" if you are on 20 m at 14.230`,
            commentFilter: `SCQP`,
            kmlFile: 'OverlaySouthCarolinaRev3.kml',
            countyNamesOverrides: {
                "Abbeville=ABB 1": "Abbeville=ABBE",
                "Aiken=AIK 1": "Aiekn=AIKE",
                "Allendale=ALL 1": "Allendale=ALLE",
                "Anderson=AND 1": "Anderson=ANDE",
                "Bamberg=BAM 1": "Bamberg=BAMB",
                "Barnwell=BRN 1": "Barnwell=BARN",
                "Beaufort=BFT 1": "Beaufort=BEAU",
                "Berkeley=BRK": "Berkeley=BERK",
                "Calhoun=CAL 1": "Calhoun=CHOU",
                "Charleston=CHA 1": "Charleston=CHAR",
                "Chester=CHR 1": "Chester=CHES",
                "Chesterfield=CHF 1": "Chesterfield=CHFD",
                "Cherokee=CHK 1": "Cherokee=CKEE",
                "Clarendon=CLR 1": "Clarendon=CLRN",
                "Colleton=COL 1": "Colleton=COLL",
                "Darlington=DAR 1": "Darlington=DARL",
                "Dillon=DIL 1": "Dillon=DILL",
                "Dorchester=DOR 1": "Dorchester=DORC",
                "Edgefield=EDG 1": "Edgefield=EDGE",
                "Fairfield=FFD 1": "Fairfield=FAIR",
                "Florence=FLO 1": "Florence=FLOR",
                "Georgetown=GEO 1": "Georgetown=GEOR",
                "Greenwood=GRW 1": "Greenwood=GRWD",
                "Greenville=GRV 1": "Greenville=GVIL",
                "Hampton=HAM 1": "Hampton=HAMP",
                "Horry=HRY 1": "Horry=HORR",
                "Jasper=JAS 1": "Jasper=JASP",
                "Kershaw=KER 1": "Kershaw=KERS",
                "Laurens=LAU 1": "Laurens=LAUR",
                "Lee=LEE 1": "Lee=LEE",
                "Lexington=LEX 1": "Lexington=LEXI",
                "Lancaster=LAN 1": "Lancaster=LNCS",
                "Marion=MRN 1": "Marion=MARI",
                "Marlboro=MRL 1": "Marlboro=MARL",
                "McCormick=MCC 1": "McCormick=MCOR",
                "Newberry=NEW 1": "Newberry=NEWB",
                "Oconee=OCO 1": "Oconee=OCON",
                "Orangeburg=ORA 1": "Orangeburg=ORNG",
                "Pickens=PIC 1": "Pickens=PICK",
                "Richland=RIC 1": "Richland=RICH",
                "Saluda=SAL 1": "Saluda=SALU",
                "Spartanburg=SPT 1": "Spartanburg=SPAR",
                "Sumter=SUM 1": "Sumter=SUMT",
                "Union=UNN 1": "Union=UNIO",
                "Williamsburg=WIL 1": "Williamsburg=WILL",
                "York=YRK 1": "York=YORK"
            }
        },
        "SD": {
            stateAbbr: "SD",
            operationTitle: `South Dakota QSO Party`,
            operationInstructions: `To be listed on this map, put <u>SDQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "SDQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `SDQP`,
            kmlFile: 'OverlaySouthDakotaRev04.kml',
        },
        "TN": {
            stateAbbr: "TN",
            operationTitle: `Tennessee QSO Party`,
            operationInstructions: `To be listed on this map, put <u>TNQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "TNQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `TNQP`,
            kmlFile: 'OverlayTennesseeRev3.kml',
        },
        "TX": {
            stateAbbr: "TX",
            operationTitle: `Texas QSO Party`,
            operationInstructions: `To be listed on this map, put <u>TXQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "TXQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `TXQP`,
            kmlFile: 'OverlayTexasRev04.kml',
        },
        "UT": {
            stateAbbr: "UT",
            operationTitle: `Utah QSO Party`,
            operationInstructions: `To be listed on this map, put <u>UTQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "UTQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `UTQP`,
            kmlFile: 'OverlayUtahRev3.kml',
        },
        "VT": {
            stateAbbr: "VT",
            operationTitle: `Vermont QSO Party`,
            operationInstructions: `To be listed on this map, put <u>VTQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "VTQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `VTQP`,
            kmlFile: 'OverlayVermont_VTQP_Rev3.kml',
        },
        "VA": {
            stateAbbr: "VA",
            operationTitle: `Virginia QSO Party`,
            operationInstructions: `To be listed on this map, put <u>VAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "VAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `VAQP`,
            kmlFile: 'OverlayVirginiaRev4.kml',
        },
        "WA": {
            stateAbbr: "WA",
            operationTitle: `Washington QSO Party`,
            operationInstructions: `To be listed on this map, put <u>WAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "WAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `WAQP`,
            kmlFile: 'OverlayWashingtonSalmonRunRev3.kml',
        },
        "WV": {
            stateAbbr: "WV",
            operationTitle: `West Virginia QSO Party`,
            operationInstructions: `To be listed on this map, put <u>WVQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "WVQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `WVQP`,
            kmlFile: 'OverlayWestVirginiaRev3.kml',
        },
        "WI": {
            stateAbbr: "WI",
            operationTitle: `Wisconsin QSO Party`,
            operationInstructions: `To be listed on this map, put <u>WIQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "WIQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `WIQP`,
            kmlFile: 'OverlayWisconsinRev8.kml',
        },
        "WY": {
            stateAbbr: "WY",
            operationTitle: `Wyoming QSO Party`,
            operationInstructions: `To be listed on this map, put <u>WYQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "WYQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `WYQP`,
            kmlFile: 'OverlayWyomingRev3.kml',
        }
    }
}
export default config;
