const config = {
    commentFilter: 'QP',
    aprsServer: "167.114.2.176",
    aprsPort: 14580,
    aprsCall: "NOCALL",
    databasePath: process.env.DB_PATH || "../aprs.db",
    logLevel: process.env.NODE_ENV === 'production' ? 'info' : 'debug',
    qsoParties: {
        "AL": {
            stateAbbr: "AL",
            operationTitle: `Alabama QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>ALQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "ALQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `ALQP`,
        },
        "AK": {
            stateAbbr: "AK",
            operationTitle: `Alaska QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>AKQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "AKQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `AKQP`,
        },
        "AZ": {
            stateAbbr: "AZ",
            operationTitle: `Arizona QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>AZQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "AZQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `AZQP`,
        },
        "AR": {
            stateAbbr: "AR",
            operationTitle: `Arkansas QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>ARQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "ARQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `ARQP`,
        },
        "CA": {
            stateAbbr: "CA",
            operationTitle: `California QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>CAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "CAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `CAQP`,
        },
        "CO": {
            stateAbbr: "CO",
            operationTitle: `Colorado QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>COQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "COQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `COQP`,
        },
        "CT": {
            stateAbbr: "CT",
            operationTitle: `Connecticut QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>CTQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "CTQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `CTQP`,
        },
        "DE": {
            stateAbbr: "DE",
            operationTitle: `Delaware QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>DEQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "DEQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `DEQP`,
        },
        "FL": {
            stateAbbr: "FL",
            operationTitle: `Florida QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>FLQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "FLQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `FLQP`,
        },
        "GA": {
            stateAbbr: "GA",
            operationTitle: `Georgia QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>GAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "GAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `GAQP`,
        },
        "HI": {
            stateAbbr: "HI",
            operationTitle: `Hawaii QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>HIQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "HIQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `HIQP`,
        },
        "ID": {
            stateAbbr: "ID",
            operationTitle: `Idaho QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>IDQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "IDQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `IDQP`,
        },
        "IL": {
            stateAbbr: "IL",
            operationTitle: `Illinois QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>ILQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "ILQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `ILQP`,
        },
        "IN": {
            stateAbbr: "IN",
            operationTitle: `Indiana QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>INQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "INQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `INQP`,
        },
        "IA": {
            stateAbbr: "IA",
            operationTitle: `Iowa QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>IAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "IAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `IAQP`,
        },
        "KS": {
            stateAbbr: "KS",
            operationTitle: `Kansas QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>KSQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "KSQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `KSQP`,
        },
        "KY": {
            stateAbbr: "KY",
            operationTitle: `Kentucky QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>KYQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "KYQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `KYQP`,
        },
        "LA": {
            stateAbbr: "LA",
            operationTitle: `Louisiana QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>LAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "LAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `LAQP`,
        },
        "ME": {
            stateAbbr: "ME",
            operationTitle: `Maine QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>MEQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MEQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MEQP`,
        },
        "MD": {
            stateAbbr: "MD",
            operationTitle: `Maryland QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>MDQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MDQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MDQP`,
        },
        "MA": {
            stateAbbr: "MA",
            operationTitle: `Massachusetts QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>MAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MAQP`,
        },
        "MI": {
            stateAbbr: "MI",
            operationTitle: `Michigan QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>MIQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MIQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MIQP`,
        },
        "MN": {
            stateAbbr: "MN",
            operationTitle: `Minnesota QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>MNQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MNQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MNQP`,
        },
        "MS": {
            stateAbbr: "MS",
            operationTitle: `Mississippi QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>MSQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MSQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MSQP`,
        },
        "MO": {
            stateAbbr: "MO",
            operationTitle: `Missouri QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>MOQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MOQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MOQP`,
        },
        "MT": {
            stateAbbr: "MT",
            operationTitle: `Montana QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>MTQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "MTQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `MTQP`,
        },
        "NE": {
            stateAbbr: "NE",
            operationTitle: `Nebraska QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>NEQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NEQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NEQP`,
        },
        "NV": {
            stateAbbr: "NV",
            operationTitle: `Nevada QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>NVQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NVQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NVQP`,
        },
        "NH": {
            stateAbbr: "NH",
            operationTitle: `New Hampshire QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>NHQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NHQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NHQP`,
        },
        "NJ": {
            stateAbbr: "NJ",
            operationTitle: `New Jersey QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>NJQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NJQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NJQP`,
        },
        "NM": {
            stateAbbr: "NM",
            operationTitle: `New Mexico QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>NMQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NMQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NMQP`,
        },
        "NY": {
            stateAbbr: "NY",
            operationTitle: `NY QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>NYQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NYQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NYQP`,
        },
        "NC": {
            stateAbbr: "NC",
            operationTitle: `North Carolina QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>NCQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NCQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NCQP`,
        },
        "ND": {
            stateAbbr: "ND",
            operationTitle: `North Dakota QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>NDQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "NDQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `NDQP`,
        },
        "OH": {
            stateAbbr: "OH",
            operationTitle: `Ohio QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>OHQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "OHQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `OHQP`,
        },
        "OK": {
            stateAbbr: "OK",
            operationTitle: `Oklahoma QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>OKQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "OKQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `OKQP`,
        },
        "OR": {
            stateAbbr: "OR",
            operationTitle: `Oregon QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>ORQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "ORQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `ORQP`,
        },
        "PA": {
            stateAbbr: "PA",
            operationTitle: `Pennsylvania QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>PAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "PAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `PAQP`,
        },
        "RI": {
            stateAbbr: "RI",
            operationTitle: `Rhode Island QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>RIQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "RIQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `RIQP`,
        },
        "SC": {
            stateAbbr: "SC",
            operationTitle: `South Carolina QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>SCQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "SCQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `SCQP`,
        },
        "SD": {
            stateAbbr: "SD",
            operationTitle: `South Dakota QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>SDQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "SDQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `SDQP`,
        },
        "TN": {
            stateAbbr: "TN",
            operationTitle: `Tennessee QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>TNQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "TNQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `TNQP`,
        },
        "TX": {
            stateAbbr: "TX",
            operationTitle: `Texas QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>TXQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "TXQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `TXQP`,
        },
        "UT": {
            stateAbbr: "UT",
            operationTitle: `Utah QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>UTQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "UTQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `UTQP`,
        },
        "VT": {
            stateAbbr: "VT",
            operationTitle: `Vermont QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>VTQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "VTQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `VTQP`,
        },
        "VA": {
            stateAbbr: "VA",
            operationTitle: `Virginia QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>VAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "VAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `VAQP`,
        },
        "WA": {
            stateAbbr: "WA",
            operationTitle: `Washington QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>WAQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "WAQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `WAQP`,
        },
        "WV": {
            stateAbbr: "WV",
            operationTitle: `West Virginia QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>WVQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "WVQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `WVQP`,
        },
        "WI": {
            stateAbbr: "WI",
            operationTitle: `Wisconsin QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>WIQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "WIQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `WIQP`,
        },
        "WY": {
            stateAbbr: "WY",
            operationTitle: `Wyoming QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>WYQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "WYQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `WYQP`,
        },
        "DC": {
            stateAbbr: "DC",
            operationTitle: `District of Columbia QSO Party`,
            operarationInstructions: `To be listed on this map, put <u>DCQP XX.XXX</u> in your APRS comment. (XX.XXX being your current frequency) Eg: "DCQP 14.230" if you are on 20mtrs at 14.230`,
            commentFilter: `DCQP`,
        }
    }
}
export default config;
